env:
  browser: true
  es6: true
  jquery: true
plugins:
  - compat
extends:
  - 'eslint:recommended'
  - 'plugin:compat/recommended'
  - 'standard'
  - 'prettier'
parserOptions:
  sourceType: module
  ecmaVersion: 2020
globals:
  # TODO: enable these Drupal globals, or remove them for non-Drupal projects
  # Drupal: readonly
  # drupalSettings: readonly
  # once: readonly
  process: readonly
ignorePatterns:
  - 'src/assets/drupal'
rules:
  array-callback-return: 0
  no-console: 1
  block-scoped-var: error
  consistent-return: error
  dot-notation: error
  eqeqeq: error
  no-empty-function: error
  no-global-assign: error
  no-self-compare: error
  vars-on-top: error
  strict:
    - error
    - global
  global-require: error
  handle-callback-err: error
  no-mixed-requires: error
  no-new: 0
  no-new-require: error
  array-bracket-spacing:
    - error
    - never
  block-spacing: error
  brace-style: error
  camelcase: 0
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  func-call-spacing:
    - error
    - never
  func-name-matching: error
  key-spacing:
    - 2
    - singleLine:
        beforeColon: false
        afterColon: true
  keyword-spacing: error
  line-comment-position:
    - error
    - position: above
  lines-around-comment:
    - error
    - beforeBlockComment: true
      beforeLineComment: false
      allowBlockStart: true
      allowObjectStart: true
      allowArrayStart: true
  lines-around-directive:
    - error
    - always
  one-var: 0
  new-cap: error
  new-parens: error
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 4
  no-inline-comments: error
  no-lonely-if: error
  no-mixed-operators: error
  no-mixed-spaces-and-tabs: error
  no-multi-assign: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
  no-nested-ternary: error
  no-new-object: error
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-tabs: 0
  no-trailing-spaces: error
  no-unused-vars: error
  no-whitespace-before-property: error
  nonblock-statement-body-position:
    - error
    - below
  object-curly-spacing: 'off'
  operator-assignment:
    - error
    - always
  quote-props:
    - error
    - consistent
  quotes:
    - error
    - single
    - avoidEscape: true
  semi: 0
  semi-spacing: error
  space-before-blocks: error
  space-before-function-paren:
    - 0
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
    - block:
        exceptions:
          - '-'
  template-tag-spacing: error
  arrow-body-style: 0
  arrow-spacing: error
  no-confusing-arrow: error
  no-const-assign: error
  no-duplicate-imports: error
  prefer-const: error
  object-shorthand: error
  no-var: error
